## global
seed:  31  # 1006 2021 101 31
device: cuda
mode: train
best_path: Null  #experiments/NYCBike1/5e5/best_model.pth   # Null 
debug: False  

## data 
data_dir: data
dataset: NYCBike1  
input_length: 19 # 4+5*3
batch_size: 32
test_batch_size: 32
graph_file: data/NYCBike1/adj_mx.npz # 128 x 128

## MoE
moe_status: True # important #
num_experts: 8
moe_dropout: 0.1
top_k: 2
moe_mlr: True  # important #
moe_add_ff: False
moe_position: 'Full'  # Full / Half / woS / woT / woST

## model 
d_input: 2                  # means inflow and outflow
d_output: 2                 # means inflow and outflow
d_model: 64
num_heads: 4
mlp_ratio: 4
encoder_depth: 1
dropout: 0.1
yita: 0.6                   # balance for inflow loss and outflow loss, $yita * inflow + (1 - yita) * outflow$
sparse: False
sparseK: 32

## train
epochs: 250
lr_init: 2.0e-3        # 0.001
scheduler: 'MultiStepLR' # StepLR MultiStepLR ExponentialLR ReduceLROnPlateau(效果一般)
step_size: 30 # StepLR
milestones: [1, 60, 90, 120, 150] # MultiStepLR
factor: 0.8 # ReduceLROnPlateau
patience: 10 # ReduceLROnPlateau
gamma: 0.5 # StepLR MultiStepLR ExponentialLR
# MultiStepLR 2.0e-3 [1, 60, 90, 120, 150] 0.5
# MultiStepLR 2.0e-3 [1, 50, 80, 100, 120] 0.5
# MultiStepLR 1.0e-4 [120, 140, 160, 180, 200] 0.9
early_stop: True
early_stop_patience: 25
grad_norm: True
max_grad_norm: 5
use_dwa: False         # whether to use dwa for loss balance
temp: 4               # tempurature parameter in dwa, a larger T means more similer weights
