## global
seed: 101  # 56 1006 2021 101 31
device: cuda
mode: train
best_path: Null 
debug: False 

## data
data_dir: data
dataset: NYCBike2 
input_length: 35
batch_size: 32
test_batch_size: 32
graph_file: data/NYCBike2/adj_mx.npz  # num_nodes 200 (20 x 10)

## MoE
moe_status: True
num_experts: 6
top_k: 2

## model 
d_input: 2                  # means inflow and outflow
d_output: 2                 # means inflow and outflow
d_model: 64
num_heads: 4
mlp_ratio: 4
encoder_depth: 1
dropout: 0.3
yita: 0.5                   # balance for inflow loss and outflow loss, $yita * inflow + (1 - yita) * outflow$

## train 
epochs: 250
lr_init: 1.0e-4        # 0.001
scheduler: 'MultiStepLR'
milestones: [120, 140, 160, 180, 200]
gamma: 0.9
early_stop: True
early_stop_patience: 25
grad_norm: True
max_grad_norm: 5
use_dwa: False         # whether to use dwa for loss balance
temp: 2               # tempurature parameter in dwa, a larger T means more similer weights
