NYCBike1:
  num_nodes: 128
  in_steps: 19
  out_steps: 1

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0003
  milestones: [20,30]
  lr_decay_rate: 0.1
  batch_size: 32
  max_epochs: 200
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  #clip_grad: 5

  model_args:
    dataset: NYCBike1
    num_nodes: 128
    in_steps: 19
    out_steps: 1
    steps_per_day: 24
    input_dim: 4
    output_dim: 2
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

NYCBike2:
  num_nodes: 200
  in_steps: 35
  out_steps: 1

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0003
  milestones: [20,30]
  lr_decay_rate: 0.1
  batch_size: 32
  max_epochs: 200
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  # clip_grad: 5

  model_args:
    dataset: NYCBike2
    num_nodes: 200
    in_steps: 35
    out_steps: 1
    steps_per_day: 48
    input_dim: 4
    output_dim: 2
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

NYCTaxi:
  num_nodes: 200
  in_steps: 35
  out_steps: 1

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0003
  milestones: [20,30]
  lr_decay_rate: 0.1
  batch_size: 32
  max_epochs: 200
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  #clip_grad: 5

  model_args:
    dataset: NYCTaxi
    num_nodes: 200
    in_steps: 35
    out_steps: 1
    steps_per_day: 48
    input_dim: 4
    output_dim: 2
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0003
  milestones: [20,30]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 200
  early_stop: 30
  use_cl: False
  cl_step_size: 2500
  #clip_grad: 5

  model_args:
    dataset: METRLA
    num_nodes: 207
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0001
  milestones: [10, 30]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300
  early_stop: 20
  use_cl: False

  model_args:
    dataset: PEMSBAY
    num_nodes: 325
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1
