## global
seed: 31
device: cuda
mode: train
best_path: None 
debug: True  

## data 
data_dir: data
dataset: NYCBike1  
input_length: 19 # 4+5*3
batch_size: 32
test_batch_size: 32
graph_file: data/NYCBike1/adj_mx.npz # 128 x 128

## model 
d_input: 2                  # means inflow and outflow
d_output: 2                 # means inflow and outflow
d_model: 64
num_heads: 4
mlp_ratio: 4
encoder_depth: 1
dropout: 0.1
yita: 0.6                   # balance for inflow loss and outflow loss, $yita * inflow + (1 - yita) * outflow$

## train
epochs: 100
lr_init: 1.0e-4        # 0.001
early_stop: True
early_stop_patience: 15
grad_norm: True
max_grad_norm: 5
use_dwa: False         # whether to use dwa for loss balance
temp: 4               # tempurature parameter in dwa, a larger T means more similer weights
