## global
seed: 31
device: cuda
mode: test
best_path: experiments/NYCBike1/Others/STSSL/20240329-130540/best_model.pth # | Null  
debug: True  

## data 
data_dir: data
dataset: NYCBike1  
input_length: 19 # 4+5*3
num_nodes: 128
batch_size: 32
test_batch_size: 32
graph_file: data/NYCBike1/adj_mx.npz # 128 x 128

## model 
d_input: 2                  # means inflow and outflow
d_output: 2                 # means inflow and outflow
d_model: 64
dropout: 0.2
percent: 0.1                # augumentation percentage  
shm_temp: 0.5               # temperature for loss of spatial heterogeneity modeling  , 0.5 is best for NYCBike
nmb_prototype: 6            # number of cluster 
yita: 0.6                   # balance for inflow loss and outflow loss, $yita * inflow + (1 - yita) * outflow$

## train
epochs: 100
lr_init: 0.001
## mask value setting ##
mask_value_train: 5.0
mask_value_test: 5.0 # 5.0 | Null $important$
## mask value setting ##
early_stop: True
early_stop_patience: 15
grad_norm: True
max_grad_norm: 5
use_dwa: True         # whether to use dwa for loss balance
temp: 4               # tempurature parameter in dwa, a larger T means more similer weights
